theme: jekyll-theme-slate

title: Skyrats Knowledge Base
description: Aqui está o conhecimento da equipe Skyrats!

defaults:
  # _docs
  - scope:
      path: "_data/navigation.yml"
      type: docs
    values:
      sidebar:
        nav: "docs"
