site_name: Knowledge Base - Skyrats
site_url: https://skyrats.github.io/knowledge_base/
site_author: Skyrats
repo_url: https://github.com/SkyRats/knowledge_base
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - About: about.md
  - 'Introdução':
    - 'Instalações': 'Introdução/Instalacao.md'
    - 'Protocolo de Segurança': 'Introdução/preflightcheck.md'
    - 'Formulário': 'Introdução/formulario.md'
  - 'Hardware':
    - 'Componentes': 'Hardware/Componentes.md'
    - 'Drones': 'Hardware/Drones.md'
    - 'Controle': 'Hardware/ControleRC.md'
    - 'Guia de Escolha de ESCs': 'Hardware/ESCs.md'
  - 'Middleware':
    - 'Calibração e Firmware': 'Middleware/Calibraçao e Firmaware.md'
    - 'Ardupilot': 'Middleware/Ardupilot.md'
  - 'Software':
    - 'Gazebo': 'Software/SIMULACAO_E_GAZEBO.md'
    - 'Convenções de Código': 'Software/Convencoes-de-Codigo.md'
  - 'Comunicação':
  - 'Workshops':
    - 'Programação Orientada a Objetos em C++': 'Workshops/workshop_oo.md'
  - 'Issue Tracker': 'https://github.com/SkyRats/knowledge_base/issues'


theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - bash
    - c
    - cpp
    - xml
    - matlab
    - python
